import React from "react";
import Navbar from "@/components/Navbar";
import "@/css/globals.css"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function MainLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <div className="max-w-[1444px] mx-auto">
            <Navbar/>
            {children}
        </div>

    )
}
